name: marketpulse
version: '1.0'
config-version: 2

profile: marketpulse

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  marketpulse:
    staging:
      +schema: "{{ env_var('DB_SCHEMA_STAGING', 'analytics_staging') }}"
      +materialized: view
    marts:
      +schema: "{{ env_var('DB_SCHEMA_MARTS', 'analytics_marts') }}"
      +materialized: view
