DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'marketpulse') THEN
    CREATE ROLE marketpulse WITH LOGIN PASSWORD 'CHANGE_ME_STRONG_PASSWORD';
  END IF;
END $$;

GRANT CONNECT ON DATABASE marketpulse TO marketpulse;

CREATE SCHEMA IF NOT EXISTS raw;
GRANT USAGE ON SCHEMA raw TO marketpulse;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA raw TO marketpulse;
ALTER DEFAULT PRIVILEGES IN SCHEMA raw GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO marketpulse;

CREATE SCHEMA IF NOT EXISTS analytics_staging;
CREATE SCHEMA IF NOT EXISTS analytics_marts;

GRANT USAGE ON SCHEMA analytics_staging TO marketpulse;
GRANT USAGE ON SCHEMA analytics_marts TO marketpulse;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA analytics_staging TO marketpulse;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA analytics_marts TO marketpulse;

ALTER DEFAULT PRIVILEGES IN SCHEMA analytics_staging GRANT ALL ON TABLES TO marketpulse;
ALTER DEFAULT PRIVILEGES IN SCHEMA analytics_marts GRANT ALL ON TABLES TO marketpulse;
